name: Auto-generate PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@v1.0.0
    # Check if the label is 'aider'
    if: github.event.label.name == 'aider'
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      # Exit if the action is taking longer than 10 minutes
      chat-timeout: 10
      #OPENAI_API_KEY
      api_key_env_name: ANTHROPIC_API_KEY
      #o3-mini-2025-01-31
      model: anthropic/claude-3-7-sonnet-latest
    secrets:
      api_key_env_value: ${{ secrets.ANTHROPIC_API_KEY }}
